// Product Database for LGM Apparel
// In production, this would come from a database/CMS

export interface Product {
  id: string
  name: string
  brand: string
  category: 'clothes' | 'accessories' | 'shoes'
  subcategory: string
  price: number
  originalPrice?: number
  description: string
  images: string[]
  colors: string[]
  sizes: string[]
  gender: 'male' | 'female' | 'unisex'
  tags: string[]
  inStock: boolean
  stockQty: number
  featured: boolean
  giftSuitable: boolean
  occasions: string[]
  style: string[]
  createdAt: string
}

export const products: Product[] = [
  // ==================== CLOTHES ====================

  // Calvin Klein - Clothes
  {
    id: 'ck-001',
    name: 'Classic Logo T-Shirt',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 't-shirts',
    price: 1899,
    originalPrice: 2499,
    description: 'Iconic Calvin Klein logo tee in premium cotton. Perfect for everyday casual wear.',
    images: ['/products/ck-tee-black.jpg'],
    colors: ['Black', 'White', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['casual', 'logo', 'cotton'],
    inStock: true,
    stockQty: 50,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-01-15'
  },
  {
    id: 'ck-002',
    name: 'Slim Fit Dress Shirt',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 'shirts',
    price: 2899,
    originalPrice: 3499,
    description: 'Elegant slim fit dress shirt. Perfect for office and formal occasions.',
    images: ['/products/ck-shirt-white.jpg'],
    colors: ['White', 'Light Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'male',
    tags: ['formal', 'office', 'slim-fit'],
    inStock: true,
    stockQty: 35,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'date-night', 'wedding-event'],
    style: ['formal-elegant', 'smart-casual'],
    createdAt: '2024-01-10'
  },
  {
    id: 'ck-003',
    name: 'Performance Boxer Briefs (3-Pack)',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 'underwear',
    price: 1599,
    description: 'Premium comfort boxer briefs. Signature CK waistband.',
    images: ['/products/ck-boxers.jpg'],
    colors: ['Black/Grey/White'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'male',
    tags: ['underwear', 'comfort', 'essentials'],
    inStock: true,
    stockQty: 100,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear'],
    style: ['minimalist'],
    createdAt: '2024-01-05'
  },
  {
    id: 'ck-004',
    name: 'Slim Fit Jeans',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 'jeans',
    price: 3499,
    originalPrice: 4299,
    description: 'Modern slim fit jeans with stretch comfort. Classic CK denim quality.',
    images: ['/products/ck-jeans.jpg'],
    colors: ['Dark Blue', 'Black', 'Light Wash'],
    sizes: ['28', '30', '32', '34', '36'],
    gender: 'male',
    tags: ['jeans', 'denim', 'slim-fit'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'date-night'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-02-01'
  },
  {
    id: 'ck-005',
    name: 'Cotton V-Neck Sweater',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 'sweaters',
    price: 2799,
    description: 'Lightweight cotton V-neck sweater. Perfect layering piece.',
    images: ['/products/ck-sweater.jpg'],
    colors: ['Grey', 'Navy', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'male',
    tags: ['sweater', 'cotton', 'layering'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear'],
    style: ['smart-casual', 'minimalist'],
    createdAt: '2024-02-05'
  },
  {
    id: 'ck-006',
    name: 'Women\'s Logo Crop Top',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 't-shirts',
    price: 1699,
    originalPrice: 2199,
    description: 'Trendy crop top with CK logo band. Soft cotton blend.',
    images: ['/products/ck-crop.jpg'],
    colors: ['Black', 'White', 'Grey'],
    sizes: ['XS', 'S', 'M', 'L'],
    gender: 'female',
    tags: ['crop-top', 'logo', 'trendy'],
    inStock: true,
    stockQty: 45,
    featured: true,
    giftSuitable: true,
    occasions: ['casual', 'gym', 'daily-wear'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-02-10'
  },
  {
    id: 'ck-007',
    name: 'Modern Cotton Bralette',
    brand: 'Calvin Klein',
    category: 'clothes',
    subcategory: 'underwear',
    price: 1299,
    description: 'Iconic modern cotton bralette with signature waistband.',
    images: ['/products/ck-bralette.jpg'],
    colors: ['Black', 'Grey', 'White'],
    sizes: ['XS', 'S', 'M', 'L'],
    gender: 'female',
    tags: ['bralette', 'cotton', 'comfort'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear'],
    style: ['minimalist'],
    createdAt: '2024-02-12'
  },

  // Nike - Clothes
  {
    id: 'nike-001',
    name: 'Tech Fleece Hoodie',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'hoodies',
    price: 4299,
    originalPrice: 5499,
    description: 'Lightweight warmth in Nike Tech Fleece. Modern slim fit with premium comfort.',
    images: ['/products/nike-hoodie-grey.jpg'],
    colors: ['Grey', 'Black', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'unisex',
    tags: ['athleisure', 'hoodie', 'tech-fleece'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'vacation', 'casual'],
    style: ['athleisure', 'casual-street'],
    createdAt: '2024-01-20'
  },
  {
    id: 'nike-002',
    name: 'Dri-FIT Training Joggers',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'pants',
    price: 2499,
    description: 'Sweat-wicking joggers for training and everyday comfort.',
    images: ['/products/nike-joggers.jpg'],
    colors: ['Black', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['training', 'joggers', 'dri-fit'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'gym'],
    style: ['athleisure'],
    createdAt: '2024-01-18'
  },
  {
    id: 'nike-003',
    name: 'Sportswear Club T-Shirt',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 't-shirts',
    price: 1299,
    description: 'Classic Nike swoosh tee. Soft cotton for all-day comfort.',
    images: ['/products/nike-tee.jpg'],
    colors: ['White', 'Black', 'Red', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'unisex',
    tags: ['casual', 'swoosh', 'cotton'],
    inStock: true,
    stockQty: 80,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'gym'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-01-12'
  },
  {
    id: 'nike-004',
    name: 'Pro Compression Shorts',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'shorts',
    price: 1799,
    description: 'High-performance compression shorts with Dri-FIT technology.',
    images: ['/products/nike-compression.jpg'],
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'male',
    tags: ['compression', 'training', 'dri-fit'],
    inStock: true,
    stockQty: 55,
    featured: false,
    giftSuitable: true,
    occasions: ['gym', 'sports'],
    style: ['athleisure'],
    createdAt: '2024-02-08'
  },
  {
    id: 'nike-005',
    name: 'Windrunner Jacket',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'jackets',
    price: 3999,
    originalPrice: 4999,
    description: 'Iconic Windrunner jacket with chevron design. Lightweight weather protection.',
    images: ['/products/nike-windrunner.jpg'],
    colors: ['Black/White', 'Navy/White', 'Red/Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['windbreaker', 'iconic', 'lightweight'],
    inStock: true,
    stockQty: 35,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'vacation', 'casual'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-02-15'
  },
  {
    id: 'nike-006',
    name: 'Women\'s One Leggings',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'leggings',
    price: 2299,
    description: 'Versatile mid-rise leggings with Dri-FIT. Perfect for training or lounging.',
    images: ['/products/nike-leggings.jpg'],
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    gender: 'female',
    tags: ['leggings', 'dri-fit', 'training'],
    inStock: true,
    stockQty: 50,
    featured: true,
    giftSuitable: true,
    occasions: ['gym', 'daily-wear', 'casual'],
    style: ['athleisure'],
    createdAt: '2024-02-18'
  },
  {
    id: 'nike-007',
    name: 'Women\'s Swoosh Sports Bra',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'sportswear',
    price: 1499,
    description: 'Medium support sports bra with iconic Swoosh. Dri-FIT technology.',
    images: ['/products/nike-sportsbra.jpg'],
    colors: ['Black', 'White', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L'],
    gender: 'female',
    tags: ['sports-bra', 'support', 'dri-fit'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
    occasions: ['gym', 'sports'],
    style: ['athleisure'],
    createdAt: '2024-02-20'
  },
  {
    id: 'nike-008',
    name: 'Sportswear Essential Fleece Pants',
    brand: 'Nike',
    category: 'clothes',
    subcategory: 'pants',
    price: 2799,
    description: 'Soft fleece pants for everyday comfort. Relaxed fit with tapered legs.',
    images: ['/products/nike-fleece-pants.jpg'],
    colors: ['Black', 'Grey Heather', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'unisex',
    tags: ['fleece', 'comfort', 'casual'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-02-22'
  },

  // GAP - Clothes
  {
    id: 'gap-001',
    name: 'Slim Fit Chinos',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'pants',
    price: 2499,
    originalPrice: 2999,
    description: 'Versatile slim fit chinos. Perfect for smart casual looks.',
    images: ['/products/gap-chinos.jpg'],
    colors: ['Khaki', 'Navy', 'Black', 'Olive'],
    sizes: ['28', '30', '32', '34', '36'],
    gender: 'male',
    tags: ['chinos', 'smart-casual', 'versatile'],
    inStock: true,
    stockQty: 45,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'date-night', 'daily-wear'],
    style: ['smart-casual', 'minimalist'],
    createdAt: '2024-01-08'
  },
  {
    id: 'gap-002',
    name: 'Vintage Soft Hoodie',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'hoodies',
    price: 1999,
    description: 'Super soft hoodie with vintage GAP logo. Ultimate comfort.',
    images: ['/products/gap-hoodie.jpg'],
    colors: ['Navy', 'Grey', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['hoodie', 'vintage', 'soft'],
    inStock: true,
    stockQty: 55,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'vacation'],
    style: ['casual-street'],
    createdAt: '2024-01-14'
  },
  {
    id: 'gap-003',
    name: 'Straight Fit Jeans',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'jeans',
    price: 2799,
    description: 'Classic straight fit jeans in premium denim.',
    images: ['/products/gap-jeans.jpg'],
    colors: ['Dark Indigo', 'Medium Wash', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    gender: 'male',
    tags: ['jeans', 'denim', 'classic'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'date-night'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-01-06'
  },
  {
    id: 'gap-004',
    name: 'Classic Oxford Shirt',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'shirts',
    price: 1999,
    originalPrice: 2499,
    description: 'Timeless oxford shirt in soft cotton. Wardrobe essential.',
    images: ['/products/gap-oxford.jpg'],
    colors: ['White', 'Light Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'male',
    tags: ['oxford', 'classic', 'cotton'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'date-night'],
    style: ['smart-casual', 'minimalist'],
    createdAt: '2024-02-25'
  },
  {
    id: 'gap-005',
    name: 'Relaxed Pocket T-Shirt',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 't-shirts',
    price: 899,
    description: 'Everyday relaxed fit tee with pocket detail. Super soft cotton.',
    images: ['/products/gap-tee.jpg'],
    colors: ['White', 'Black', 'Navy', 'Grey', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['t-shirt', 'pocket', 'relaxed'],
    inStock: true,
    stockQty: 80,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-02-28'
  },
  {
    id: 'gap-006',
    name: 'Denim Jacket',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'jackets',
    price: 3499,
    originalPrice: 4299,
    description: 'Classic denim jacket with authentic wash. Timeless style.',
    images: ['/products/gap-denim-jacket.jpg'],
    colors: ['Medium Wash', 'Dark Wash', 'Light Wash'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['denim', 'jacket', 'classic'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
    occasions: ['casual', 'daily-wear', 'vacation'],
    style: ['casual-street'],
    createdAt: '2024-03-01'
  },
  {
    id: 'gap-007',
    name: 'Women\'s High Rise Skinny Jeans',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'jeans',
    price: 2999,
    description: 'Flattering high-rise skinny jeans with stretch comfort.',
    images: ['/products/gap-skinny.jpg'],
    colors: ['Dark Indigo', 'Black', 'Medium Wash'],
    sizes: ['24', '26', '28', '30', '32'],
    gender: 'female',
    tags: ['skinny', 'high-rise', 'stretch'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'date-night'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-03-03'
  },
  {
    id: 'gap-008',
    name: 'Cotton Cardigan',
    brand: 'GAP',
    category: 'clothes',
    subcategory: 'sweaters',
    price: 2299,
    description: 'Lightweight cotton cardigan. Perfect for layering.',
    images: ['/products/gap-cardigan.jpg'],
    colors: ['Navy', 'Grey', 'Cream'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['cardigan', 'cotton', 'layering'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear'],
    style: ['smart-casual', 'minimalist'],
    createdAt: '2024-03-05'
  },

  // Ralph Lauren - Clothes
  {
    id: 'rl-001',
    name: 'Classic Fit Polo Shirt',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'polos',
    price: 3299,
    originalPrice: 3999,
    description: 'Iconic Ralph Lauren polo with signature pony logo. Timeless style.',
    images: ['/products/rl-polo.jpg'],
    colors: ['Navy', 'White', 'Red', 'Green'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'male',
    tags: ['polo', 'classic', 'preppy'],
    inStock: true,
    stockQty: 35,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'date-night'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-01-22'
  },
  {
    id: 'rl-002',
    name: 'Wool Blend Blazer',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'blazers',
    price: 8999,
    originalPrice: 10999,
    description: 'Premium wool blend blazer. Perfect for formal occasions.',
    images: ['/products/rl-blazer.jpg'],
    colors: ['Navy', 'Charcoal'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'male',
    tags: ['blazer', 'formal', 'wool'],
    inStock: true,
    stockQty: 15,
    featured: true,
    giftSuitable: true,
    occasions: ['wedding-event', 'work-office', 'date-night'],
    style: ['formal-elegant'],
    createdAt: '2024-01-25'
  },
  {
    id: 'rl-003',
    name: 'Cable Knit Sweater',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'sweaters',
    price: 4599,
    description: 'Classic cable knit sweater in soft cotton blend.',
    images: ['/products/rl-sweater.jpg'],
    colors: ['Cream', 'Navy', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['sweater', 'cable-knit', 'classic'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'date-night', 'vacation'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-01-16'
  },
  {
    id: 'rl-004',
    name: 'Slim Fit Chino Pants',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'pants',
    price: 4299,
    description: 'Refined slim fit chinos with stretch. Premium quality.',
    images: ['/products/rl-chinos.jpg'],
    colors: ['Khaki', 'Navy', 'Grey', 'Olive'],
    sizes: ['28', '30', '32', '34', '36'],
    gender: 'male',
    tags: ['chinos', 'slim-fit', 'premium'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'date-night'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-03-08'
  },
  {
    id: 'rl-005',
    name: 'Oxford Button-Down Shirt',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'shirts',
    price: 3799,
    originalPrice: 4499,
    description: 'Premium oxford cloth shirt with signature pony. Timeless American style.',
    images: ['/products/rl-oxford.jpg'],
    colors: ['White', 'Blue', 'Pink', 'Striped'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'male',
    tags: ['oxford', 'button-down', 'classic'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'date-night'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-03-10'
  },
  {
    id: 'rl-006',
    name: 'Women\'s Slim Fit Polo',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'polos',
    price: 2999,
    description: 'Classic polo shirt designed for women. Signature pony embroidery.',
    images: ['/products/rl-womens-polo.jpg'],
    colors: ['White', 'Navy', 'Pink', 'Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    gender: 'female',
    tags: ['polo', 'classic', 'preppy'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'casual'],
    style: ['smart-casual'],
    createdAt: '2024-03-12'
  },
  {
    id: 'rl-007',
    name: 'Cotton Crew Neck T-Shirt',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 't-shirts',
    price: 1999,
    description: 'Soft cotton tee with embroidered pony. Premium essential.',
    images: ['/products/rl-tee.jpg'],
    colors: ['White', 'Black', 'Navy', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    gender: 'unisex',
    tags: ['t-shirt', 'cotton', 'essential'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-03-14'
  },
  {
    id: 'rl-008',
    name: 'Quilted Vest',
    brand: 'Ralph Lauren',
    category: 'clothes',
    subcategory: 'vests',
    price: 5499,
    originalPrice: 6499,
    description: 'Lightweight quilted vest. Perfect for layering in transitional weather.',
    images: ['/products/rl-vest.jpg'],
    colors: ['Navy', 'Black', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'male',
    tags: ['vest', 'quilted', 'layering'],
    inStock: true,
    stockQty: 20,
    featured: false,
    giftSuitable: true,
    occasions: ['casual', 'vacation', 'daily-wear'],
    style: ['smart-casual'],
    createdAt: '2024-03-16'
  },

  // ==================== ACCESSORIES ====================

  // Michael Kors - Accessories
  {
    id: 'mk-001',
    name: 'Lexington Chronograph Watch',
    brand: 'Michael Kors',
    category: 'accessories',
    subcategory: 'watches',
    price: 7500,
    originalPrice: 8999,
    description: 'Stunning chronograph watch with gold-tone finish. Statement piece.',
    images: ['/products/mk-watch-gold.jpg'],
    colors: ['Gold', 'Silver', 'Rose Gold'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['watch', 'chronograph', 'luxury'],
    inStock: true,
    stockQty: 20,
    featured: true,
    giftSuitable: true,
    occasions: ['date-night', 'wedding-event', 'work-office'],
    style: ['formal-elegant', 'smart-casual'],
    createdAt: '2024-01-28'
  },
  {
    id: 'mk-002',
    name: 'Jet Set Crossbody Bag',
    brand: 'Michael Kors',
    category: 'accessories',
    subcategory: 'bags',
    price: 4500,
    originalPrice: 5499,
    description: 'Chic crossbody bag in signature MK print. Perfect everyday accessory.',
    images: ['/products/mk-bag.jpg'],
    colors: ['Brown/Tan', 'Black', 'Navy'],
    sizes: ['One Size'],
    gender: 'female',
    tags: ['bag', 'crossbody', 'signature'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'work-office', 'date-night'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-01-26'
  },
  {
    id: 'mk-003',
    name: 'Leather Card Holder',
    brand: 'Michael Kors',
    category: 'accessories',
    subcategory: 'wallets',
    price: 1899,
    description: 'Slim leather card holder. Compact and stylish.',
    images: ['/products/mk-cardholder.jpg'],
    colors: ['Black', 'Brown', 'Navy'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['wallet', 'card-holder', 'leather'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear'],
    style: ['minimalist', 'smart-casual'],
    createdAt: '2024-01-20'
  },
  {
    id: 'mk-004',
    name: 'Signature Tote Bag',
    brand: 'Michael Kors',
    category: 'accessories',
    subcategory: 'bags',
    price: 6999,
    originalPrice: 8499,
    description: 'Spacious tote with MK signature print. Perfect for work or travel.',
    images: ['/products/mk-tote.jpg'],
    colors: ['Brown/Tan', 'Black', 'Vanilla'],
    sizes: ['One Size'],
    gender: 'female',
    tags: ['tote', 'signature', 'spacious'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'travel'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-03-18'
  },
  {
    id: 'mk-005',
    name: 'Darci Watch',
    brand: 'Michael Kors',
    category: 'accessories',
    subcategory: 'watches',
    price: 6500,
    description: 'Elegant Darci watch with crystal accents. Feminine sophistication.',
    images: ['/products/mk-darci.jpg'],
    colors: ['Silver', 'Gold', 'Rose Gold'],
    sizes: ['One Size'],
    gender: 'female',
    tags: ['watch', 'crystal', 'elegant'],
    inStock: true,
    stockQty: 18,
    featured: false,
    giftSuitable: true,
    occasions: ['date-night', 'wedding-event', 'daily-wear'],
    style: ['formal-elegant'],
    createdAt: '2024-03-20'
  },
  {
    id: 'mk-006',
    name: 'Leather Bifold Wallet',
    brand: 'Michael Kors',
    category: 'accessories',
    subcategory: 'wallets',
    price: 2999,
    description: 'Classic bifold wallet in premium leather. Multiple card slots.',
    images: ['/products/mk-wallet.jpg'],
    colors: ['Black', 'Brown'],
    sizes: ['One Size'],
    gender: 'male',
    tags: ['wallet', 'bifold', 'leather'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear'],
    style: ['smart-casual', 'minimalist'],
    createdAt: '2024-03-22'
  },

  // Calvin Klein - Accessories
  {
    id: 'ck-acc-001',
    name: 'Reversible Leather Belt',
    brand: 'Calvin Klein',
    category: 'accessories',
    subcategory: 'belts',
    price: 1899,
    originalPrice: 2299,
    description: 'Reversible leather belt with signature CK buckle. Two looks in one.',
    images: ['/products/ck-belt.jpg'],
    colors: ['Black/Brown'],
    sizes: ['32', '34', '36', '38', '40'],
    gender: 'male',
    tags: ['belt', 'leather', 'reversible'],
    inStock: true,
    stockQty: 45,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'date-night'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-01-18'
  },
  {
    id: 'ck-acc-002',
    name: 'Minimal Watch',
    brand: 'Calvin Klein',
    category: 'accessories',
    subcategory: 'watches',
    price: 5999,
    description: 'Sleek minimalist watch with mesh strap. Swiss movement.',
    images: ['/products/ck-watch.jpg'],
    colors: ['Silver', 'Gold', 'Black'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['watch', 'minimal', 'swiss'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'work-office', 'date-night'],
    style: ['minimalist', 'smart-casual'],
    createdAt: '2024-01-24'
  },
  {
    id: 'ck-acc-003',
    name: 'Leather Crossbody Bag',
    brand: 'Calvin Klein',
    category: 'accessories',
    subcategory: 'bags',
    price: 3499,
    originalPrice: 4299,
    description: 'Sleek leather crossbody bag with CK hardware. Modern essential.',
    images: ['/products/ck-crossbody.jpg'],
    colors: ['Black', 'Navy', 'Tan'],
    sizes: ['One Size'],
    gender: 'female',
    tags: ['crossbody', 'leather', 'modern'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'work-office'],
    style: ['minimalist', 'smart-casual'],
    createdAt: '2024-03-24'
  },
  {
    id: 'ck-acc-004',
    name: 'Sunglasses',
    brand: 'Calvin Klein',
    category: 'accessories',
    subcategory: 'eyewear',
    price: 4999,
    description: 'Classic aviator sunglasses with CK branding. UV protection.',
    images: ['/products/ck-sunglasses.jpg'],
    colors: ['Black', 'Gold/Brown', 'Silver/Blue'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['sunglasses', 'aviator', 'uv-protection'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['vacation', 'daily-wear', 'casual'],
    style: ['casual-street', 'smart-casual'],
    createdAt: '2024-03-26'
  },

  // Nike - Accessories
  {
    id: 'nike-acc-001',
    name: 'Heritage Backpack',
    brand: 'Nike',
    category: 'accessories',
    subcategory: 'bags',
    price: 1999,
    description: 'Classic Nike backpack with padded straps. Durable and spacious.',
    images: ['/products/nike-backpack.jpg'],
    colors: ['Black', 'Navy', 'Grey'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['backpack', 'heritage', 'durable'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'gym', 'school'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-03-28'
  },
  {
    id: 'nike-acc-002',
    name: 'Futura Cap',
    brand: 'Nike',
    category: 'accessories',
    subcategory: 'hats',
    price: 999,
    description: 'Classic Nike cap with embroidered Swoosh. Adjustable fit.',
    images: ['/products/nike-cap.jpg'],
    colors: ['Black', 'White', 'Navy', 'Red'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['cap', 'swoosh', 'adjustable'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
    occasions: ['casual', 'gym', 'daily-wear'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-03-30'
  },
  {
    id: 'nike-acc-003',
    name: 'Gym Duffle Bag',
    brand: 'Nike',
    category: 'accessories',
    subcategory: 'bags',
    price: 2499,
    description: 'Spacious duffle bag for training essentials. Separate shoe compartment.',
    images: ['/products/nike-duffle.jpg'],
    colors: ['Black', 'Grey', 'Navy'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['duffle', 'gym', 'spacious'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['gym', 'travel', 'sports'],
    style: ['athleisure'],
    createdAt: '2024-04-01'
  },
  {
    id: 'nike-acc-004',
    name: 'Everyday Crew Socks (3-Pack)',
    brand: 'Nike',
    category: 'accessories',
    subcategory: 'socks',
    price: 699,
    description: 'Cushioned crew socks with Dri-FIT. Everyday comfort.',
    images: ['/products/nike-socks.jpg'],
    colors: ['White', 'Black', 'Mixed'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['socks', 'dri-fit', 'cushioned'],
    inStock: true,
    stockQty: 100,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'gym', 'sports'],
    style: ['athleisure'],
    createdAt: '2024-04-03'
  },

  // Ralph Lauren - Accessories
  {
    id: 'rl-acc-001',
    name: 'Leather Belt',
    brand: 'Ralph Lauren',
    category: 'accessories',
    subcategory: 'belts',
    price: 2999,
    description: 'Premium leather belt with pony logo buckle. Timeless style.',
    images: ['/products/rl-belt.jpg'],
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['32', '34', '36', '38', '40'],
    gender: 'male',
    tags: ['belt', 'leather', 'premium'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'date-night'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-04-05'
  },
  {
    id: 'rl-acc-002',
    name: 'Pony Baseball Cap',
    brand: 'Ralph Lauren',
    category: 'accessories',
    subcategory: 'hats',
    price: 1799,
    description: 'Classic baseball cap with signature pony embroidery.',
    images: ['/products/rl-cap.jpg'],
    colors: ['Navy', 'White', 'Black', 'Red'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['cap', 'baseball', 'pony'],
    inStock: true,
    stockQty: 45,
    featured: true,
    giftSuitable: true,
    occasions: ['casual', 'vacation', 'daily-wear'],
    style: ['casual-street', 'smart-casual'],
    createdAt: '2024-04-07'
  },
  {
    id: 'rl-acc-003',
    name: 'Silk Tie',
    brand: 'Ralph Lauren',
    category: 'accessories',
    subcategory: 'ties',
    price: 2499,
    description: 'Luxurious silk tie with classic pattern. Perfect for formal occasions.',
    images: ['/products/rl-tie.jpg'],
    colors: ['Navy Stripe', 'Burgundy', 'Grey Pattern'],
    sizes: ['One Size'],
    gender: 'male',
    tags: ['tie', 'silk', 'formal'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
    occasions: ['wedding-event', 'work-office', 'date-night'],
    style: ['formal-elegant'],
    createdAt: '2024-04-09'
  },
  {
    id: 'rl-acc-004',
    name: 'Leather Wallet',
    brand: 'Ralph Lauren',
    category: 'accessories',
    subcategory: 'wallets',
    price: 3999,
    description: 'Premium leather bifold wallet with pony embossing.',
    images: ['/products/rl-wallet.jpg'],
    colors: ['Black', 'Brown'],
    sizes: ['One Size'],
    gender: 'male',
    tags: ['wallet', 'leather', 'bifold'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-04-11'
  },

  // GAP - Accessories
  {
    id: 'gap-acc-001',
    name: 'Canvas Tote Bag',
    brand: 'GAP',
    category: 'accessories',
    subcategory: 'bags',
    price: 1499,
    description: 'Casual canvas tote with GAP logo. Perfect everyday bag.',
    images: ['/products/gap-tote.jpg'],
    colors: ['Natural', 'Navy', 'Grey'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['tote', 'canvas', 'casual'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'shopping'],
    style: ['casual-street'],
    createdAt: '2024-04-13'
  },
  {
    id: 'gap-acc-002',
    name: 'Ribbed Beanie',
    brand: 'GAP',
    category: 'accessories',
    subcategory: 'hats',
    price: 799,
    description: 'Cozy ribbed beanie with GAP logo. Soft acrylic knit.',
    images: ['/products/gap-beanie.jpg'],
    colors: ['Navy', 'Grey', 'Black', 'Burgundy'],
    sizes: ['One Size'],
    gender: 'unisex',
    tags: ['beanie', 'ribbed', 'cozy'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
    occasions: ['casual', 'vacation', 'daily-wear'],
    style: ['casual-street'],
    createdAt: '2024-04-15'
  },
  {
    id: 'gap-acc-003',
    name: 'Leather Braided Belt',
    brand: 'GAP',
    category: 'accessories',
    subcategory: 'belts',
    price: 1299,
    description: 'Casual braided leather belt. Versatile everyday accessory.',
    images: ['/products/gap-belt.jpg'],
    colors: ['Brown', 'Tan', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    gender: 'unisex',
    tags: ['belt', 'braided', 'casual'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
    occasions: ['casual', 'daily-wear'],
    style: ['casual-street'],
    createdAt: '2024-04-17'
  },

  // ==================== SHOES ====================

  // Nike - Shoes
  {
    id: 'nike-shoe-001',
    name: 'Air Max 90',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 6995,
    originalPrice: 7995,
    description: 'Iconic Air Max 90 with visible Air unit. Legendary comfort and style.',
    images: ['/products/nike-airmax90.jpg'],
    colors: ['White', 'Black', 'Grey'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'air-max', 'iconic'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-01-30'
  },
  {
    id: 'nike-shoe-002',
    name: 'Dunk Low Retro',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 5495,
    description: 'Classic Dunk Low in retro colorway. Street style essential.',
    images: ['/products/nike-dunk.jpg'],
    colors: ['Panda (Black/White)', 'Grey Fog', 'University Red'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'dunk', 'retro'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'party'],
    style: ['casual-street', 'trendy'],
    createdAt: '2024-01-29'
  },
  {
    id: 'nike-shoe-003',
    name: 'Court Vision Low',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 3995,
    description: 'Clean court-inspired sneaker. Versatile everyday style.',
    images: ['/products/nike-court.jpg'],
    colors: ['White', 'White/Black'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'court', 'clean'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'work-office'],
    style: ['minimalist', 'smart-casual'],
    createdAt: '2024-01-22'
  },
  {
    id: 'nike-shoe-004',
    name: 'Air Force 1 \'07',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 5495,
    description: 'The legendary Air Force 1. Timeless basketball heritage.',
    images: ['/products/nike-af1.jpg'],
    colors: ['White', 'Black', 'White/Black'],
    sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
    gender: 'unisex',
    tags: ['sneakers', 'air-force', 'legendary'],
    inStock: true,
    stockQty: 50,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street'],
    createdAt: '2024-04-19'
  },
  {
    id: 'nike-shoe-005',
    name: 'Air Jordan 1 Low',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 6995,
    originalPrice: 7995,
    description: 'Iconic Air Jordan 1 in low-top silhouette. Street legend.',
    images: ['/products/nike-aj1-low.jpg'],
    colors: ['White/Black', 'Chicago', 'Shadow Grey'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'jordan', 'iconic'],
    inStock: true,
    stockQty: 20,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'party'],
    style: ['casual-street', 'trendy'],
    createdAt: '2024-04-21'
  },
  {
    id: 'nike-shoe-006',
    name: 'Revolution 6 Running Shoes',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'running',
    price: 3495,
    description: 'Lightweight running shoes with soft cushioning. Perfect for daily runs.',
    images: ['/products/nike-revolution.jpg'],
    colors: ['Black/White', 'Grey/Green', 'Navy/Red'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['running', 'lightweight', 'cushioning'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
    occasions: ['gym', 'running', 'sports'],
    style: ['athleisure'],
    createdAt: '2024-04-23'
  },
  {
    id: 'nike-shoe-007',
    name: 'Blazer Mid \'77',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 4995,
    description: 'Vintage basketball style meets modern comfort. Classic Blazer.',
    images: ['/products/nike-blazer.jpg'],
    colors: ['White/Black', 'White/Green', 'White/Red'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'blazer', 'vintage'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'trendy'],
    createdAt: '2024-04-25'
  },
  {
    id: 'nike-shoe-008',
    name: 'Women\'s Air Max 270',
    brand: 'Nike',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 7495,
    originalPrice: 8495,
    description: 'Bold Air Max with largest heel Air unit. All-day comfort.',
    images: ['/products/nike-airmax270.jpg'],
    colors: ['Black/White', 'White/Pink', 'Grey/Purple'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    gender: 'female',
    tags: ['sneakers', 'air-max', 'cushioned'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street', 'athleisure'],
    createdAt: '2024-04-27'
  },

  // Ralph Lauren - Shoes
  {
    id: 'rl-shoe-001',
    name: 'Leather Penny Loafers',
    brand: 'Ralph Lauren',
    category: 'shoes',
    subcategory: 'loafers',
    price: 6999,
    description: 'Classic penny loafers in premium leather. Timeless sophistication.',
    images: ['/products/rl-loafers.jpg'],
    colors: ['Brown', 'Black', 'Burgundy'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'male',
    tags: ['loafers', 'leather', 'classic'],
    inStock: true,
    stockQty: 20,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'date-night', 'wedding-event'],
    style: ['formal-elegant', 'smart-casual'],
    createdAt: '2024-01-27'
  },
  {
    id: 'rl-shoe-002',
    name: 'Canvas Sneakers',
    brand: 'Ralph Lauren',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 2999,
    description: 'Casual canvas sneakers with signature pony logo.',
    images: ['/products/rl-canvas.jpg'],
    colors: ['White', 'Navy', 'Grey'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'canvas', 'casual'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'vacation'],
    style: ['smart-casual', 'casual-street'],
    createdAt: '2024-01-19'
  },
  {
    id: 'rl-shoe-003',
    name: 'Leather Boat Shoes',
    brand: 'Ralph Lauren',
    category: 'shoes',
    subcategory: 'boat-shoes',
    price: 4999,
    description: 'Classic boat shoes in premium leather. Nautical style.',
    images: ['/products/rl-boat.jpg'],
    colors: ['Brown', 'Navy', 'Tan'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'male',
    tags: ['boat-shoes', 'leather', 'nautical'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
    occasions: ['casual', 'vacation', 'date-night'],
    style: ['smart-casual'],
    createdAt: '2024-04-29'
  },
  {
    id: 'rl-shoe-004',
    name: 'Leather Dress Oxford',
    brand: 'Ralph Lauren',
    category: 'shoes',
    subcategory: 'oxfords',
    price: 7999,
    originalPrice: 9499,
    description: 'Premium leather oxford shoes. Perfect for formal occasions.',
    images: ['/products/rl-oxford-shoe.jpg'],
    colors: ['Black', 'Brown'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'male',
    tags: ['oxford', 'formal', 'leather'],
    inStock: true,
    stockQty: 15,
    featured: true,
    giftSuitable: true,
    occasions: ['wedding-event', 'work-office', 'date-night'],
    style: ['formal-elegant'],
    createdAt: '2024-05-01'
  },

  // Calvin Klein - Shoes
  {
    id: 'ck-shoe-001',
    name: 'Leather Sneakers',
    brand: 'Calvin Klein',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 4499,
    originalPrice: 5499,
    description: 'Sleek leather sneakers with CK branding. Minimalist design.',
    images: ['/products/ck-sneakers.jpg'],
    colors: ['White', 'Black', 'Navy'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sneakers', 'leather', 'minimal'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'work-office', 'casual'],
    style: ['minimalist', 'smart-casual'],
    createdAt: '2024-05-03'
  },
  {
    id: 'ck-shoe-002',
    name: 'Canvas Slip-Ons',
    brand: 'Calvin Klein',
    category: 'shoes',
    subcategory: 'slip-ons',
    price: 2999,
    description: 'Easy slip-on sneakers in canvas. CK logo detail.',
    images: ['/products/ck-slipons.jpg'],
    colors: ['Black', 'White', 'Navy'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['slip-on', 'canvas', 'easy'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'vacation'],
    style: ['casual-street', 'minimalist'],
    createdAt: '2024-05-05'
  },
  {
    id: 'ck-shoe-003',
    name: 'Women\'s Ankle Boots',
    brand: 'Calvin Klein',
    category: 'shoes',
    subcategory: 'boots',
    price: 5999,
    originalPrice: 7499,
    description: 'Sleek ankle boots with block heel. Modern sophistication.',
    images: ['/products/ck-boots.jpg'],
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    gender: 'female',
    tags: ['boots', 'ankle', 'heeled'],
    inStock: true,
    stockQty: 20,
    featured: true,
    giftSuitable: true,
    occasions: ['work-office', 'date-night', 'daily-wear'],
    style: ['formal-elegant', 'smart-casual'],
    createdAt: '2024-05-07'
  },

  // GAP - Shoes
  {
    id: 'gap-shoe-001',
    name: 'Classic Canvas Sneakers',
    brand: 'GAP',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 1999,
    description: 'Simple canvas sneakers for everyday wear. Timeless style.',
    images: ['/products/gap-canvas.jpg'],
    colors: ['White', 'Black', 'Navy', 'Red'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['canvas', 'sneakers', 'casual'],
    inStock: true,
    stockQty: 55,
    featured: false,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual'],
    style: ['casual-street'],
    createdAt: '2024-05-09'
  },
  {
    id: 'gap-shoe-002',
    name: 'Suede Chukka Boots',
    brand: 'GAP',
    category: 'shoes',
    subcategory: 'boots',
    price: 3499,
    originalPrice: 4299,
    description: 'Casual chukka boots in soft suede. Versatile style.',
    images: ['/products/gap-chukka.jpg'],
    colors: ['Tan', 'Grey', 'Brown'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    gender: 'male',
    tags: ['chukka', 'suede', 'boots'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'date-night'],
    style: ['smart-casual', 'casual-street'],
    createdAt: '2024-05-11'
  },
  {
    id: 'gap-shoe-003',
    name: 'Women\'s Ballet Flats',
    brand: 'GAP',
    category: 'shoes',
    subcategory: 'flats',
    price: 1799,
    description: 'Classic ballet flats in soft leather. Comfortable and chic.',
    images: ['/products/gap-flats.jpg'],
    colors: ['Black', 'Nude', 'Red', 'Navy'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    gender: 'female',
    tags: ['flats', 'ballet', 'leather'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'casual'],
    style: ['minimalist', 'smart-casual'],
    createdAt: '2024-05-13'
  },
  {
    id: 'gap-shoe-004',
    name: 'Leather Sandals',
    brand: 'GAP',
    category: 'shoes',
    subcategory: 'sandals',
    price: 2299,
    description: 'Comfortable leather sandals for warm days. Classic design.',
    images: ['/products/gap-sandals.jpg'],
    colors: ['Brown', 'Tan', 'Black'],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    gender: 'unisex',
    tags: ['sandals', 'leather', 'summer'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
    occasions: ['vacation', 'casual', 'daily-wear'],
    style: ['casual-street'],
    createdAt: '2024-05-15'
  },

  // Michael Kors - Shoes
  {
    id: 'mk-shoe-001',
    name: 'Women\'s Logo Sneakers',
    brand: 'Michael Kors',
    category: 'shoes',
    subcategory: 'sneakers',
    price: 4999,
    originalPrice: 5999,
    description: 'Trendy sneakers with MK signature print. Fashion-forward style.',
    images: ['/products/mk-sneakers.jpg'],
    colors: ['White/Brown', 'Black', 'Vanilla'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    gender: 'female',
    tags: ['sneakers', 'logo', 'fashion'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
    occasions: ['daily-wear', 'casual', 'shopping'],
    style: ['smart-casual', 'trendy'],
    createdAt: '2024-05-17'
  },
  {
    id: 'mk-shoe-002',
    name: 'Women\'s Heeled Sandals',
    brand: 'Michael Kors',
    category: 'shoes',
    subcategory: 'sandals',
    price: 5499,
    description: 'Elegant heeled sandals with MK hardware. Perfect for events.',
    images: ['/products/mk-heels.jpg'],
    colors: ['Black', 'Nude', 'Gold'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    gender: 'female',
    tags: ['heels', 'sandals', 'elegant'],
    inStock: true,
    stockQty: 20,
    featured: true,
    giftSuitable: true,
    occasions: ['date-night', 'wedding-event', 'party'],
    style: ['formal-elegant'],
    createdAt: '2024-05-19'
  },
  {
    id: 'mk-shoe-003',
    name: 'Women\'s Leather Loafers',
    brand: 'Michael Kors',
    category: 'shoes',
    subcategory: 'loafers',
    price: 4499,
    description: 'Chic leather loafers with MK charm. Effortless elegance.',
    images: ['/products/mk-loafers.jpg'],
    colors: ['Black', 'Brown', 'Cream'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    gender: 'female',
    tags: ['loafers', 'leather', 'chic'],
    inStock: true,
    stockQty: 28,
    featured: false,
    giftSuitable: true,
    occasions: ['work-office', 'daily-wear', 'casual'],
    style: ['smart-casual', 'formal-elegant'],
    createdAt: '2024-05-21'
  },
]

// Helper functions
export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter(p => p.category === category)
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter(p => p.brand === brand)
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured)
}

export function getGiftSuitableProducts(): Product[] {
  return products.filter(p => p.giftSuitable)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.brand.toLowerCase().includes(lowerQuery) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery)) ||
    p.description.toLowerCase().includes(lowerQuery)
  )
}

export function filterProducts(filters: {
  category?: string
  brand?: string
  gender?: string
  minPrice?: number
  maxPrice?: number
  style?: string
  occasion?: string
}): Product[] {
  return products.filter(p => {
    if (filters.category && p.category !== filters.category) return false
    if (filters.brand && p.brand !== filters.brand) return false
    if (filters.gender && p.gender !== filters.gender && p.gender !== 'unisex') return false
    if (filters.minPrice && p.price < filters.minPrice) return false
    if (filters.maxPrice && p.price > filters.maxPrice) return false
    if (filters.style && !p.style.includes(filters.style)) return false
    if (filters.occasion && !p.occasions.includes(filters.occasion)) return false
    return true
  })
}

export const brands = [
  // Premium Brands
  'Calvin Klein',
  'Ralph Lauren',
  'Michael Kors',
  'Tommy Hilfiger',
  'Coach',
  'Kate Spade',
  'Guess',
  // Athletic/Sportswear
  'Nike',
  'Adidas',
  'Puma',
  'Under Armour',
  'New Balance',
  'Reebok',
  'Fila',
  // Casual/Fast Fashion
  'GAP',
  'H&M',
  'Zara',
  'Uniqlo',
  'Mango',
  'Forever 21',
  // Denim
  'Levi\'s',
  'Wrangler',
  'Lee',
  // Luxury
  'Lacoste',
  'Fred Perry',
  'Hugo Boss',
  // Other
  'Other'
]
export const categories = ['clothes', 'accessories', 'shoes'] as const
