// Sample products for seeding the database
// 50+ products across different categories, genders, and price points

export interface SampleProduct {
  name: string
  brand: string
  price: number
  originalPrice?: number
  category: 'clothes' | 'accessories' | 'shoes'
  subcategory: string
  gender: 'male' | 'female' | 'unisex'
  colors: string[]
  sizes: string[]
  style: string[]
  occasions: string[]
  tags: string[]
  description: string
  images: string[]
  inStock: boolean
  stockQty: number
  featured: boolean
  giftSuitable: boolean
}

export const sampleProducts: SampleProduct[] = [
  // ==================== MEN'S CLOTHING (18 products) ====================
  {
    name: 'Slim Fit Polo Shirt',
    brand: 'Bench',
    price: 1299,
    category: 'clothes',
    subcategory: 'polo',
    gender: 'male',
    colors: ['Navy', 'White', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['smart-casual'],
    occasions: ['daily-wear', 'work-office'],
    tags: ['polo', 'slim-fit', 'cotton'],
    description: 'Classic slim fit polo shirt perfect for casual and office wear.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Stretch Chino Pants',
    brand: 'Uniqlo',
    price: 1990,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'male',
    colors: ['Khaki', 'Navy', 'Black'],
    sizes: ['28', '30', '32', '34'],
    style: ['smart-casual'],
    occasions: ['work-office', 'date-night'],
    tags: ['chinos', 'stretch', 'comfortable'],
    description: 'Comfortable stretch chino pants for a polished casual look.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Oversized Graphic Tee',
    brand: 'Penshoppe',
    price: 699,
    category: 'clothes',
    subcategory: 't-shirts',
    gender: 'male',
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'party'],
    tags: ['graphic', 'oversized', 'streetwear'],
    description: 'Trendy oversized graphic tee for a relaxed streetwear vibe.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Classic Denim Jacket',
    brand: "Levi's",
    price: 4500,
    category: 'clothes',
    subcategory: 'jackets',
    gender: 'male',
    colors: ['Blue', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['denim', 'jacket', 'classic'],
    description: 'Iconic denim jacket that never goes out of style.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 25,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Performance Polo Shirt',
    brand: 'Nike',
    price: 2295,
    category: 'clothes',
    subcategory: 'polo',
    gender: 'male',
    colors: ['Navy', 'Gray', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['athleisure'],
    occasions: ['daily-wear', 'work-office'],
    tags: ['performance', 'dri-fit', 'athletic'],
    description: 'Moisture-wicking polo shirt for active lifestyles.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Essential Jogger Pants',
    brand: 'Adidas',
    price: 2800,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'male',
    colors: ['Black', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['casual-street', 'athleisure'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['joggers', 'comfortable', 'athletic'],
    description: 'Comfortable jogger pants with iconic three stripes.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 55,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Formal Dress Shirt',
    brand: 'Marks & Spencer',
    price: 2490,
    category: 'clothes',
    subcategory: 'shirts',
    gender: 'male',
    colors: ['White', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['formal-elegant'],
    occasions: ['work-office', 'wedding-event'],
    tags: ['formal', 'dress-shirt', 'cotton'],
    description: 'Premium dress shirt for formal occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Cargo Shorts',
    brand: 'Bench',
    price: 1299,
    category: 'clothes',
    subcategory: 'shorts',
    gender: 'male',
    colors: ['Olive', 'Khaki'],
    sizes: ['28', '30', '32', '34'],
    style: ['casual-street'],
    occasions: ['vacation', 'daily-wear'],
    tags: ['cargo', 'shorts', 'casual'],
    description: 'Practical cargo shorts with multiple pockets.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Bomber Jacket',
    brand: 'Zara',
    price: 3995,
    category: 'clothes',
    subcategory: 'jackets',
    gender: 'male',
    colors: ['Black', 'Navy', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'date-night'],
    tags: ['bomber', 'jacket', 'trendy'],
    description: 'Classic bomber jacket with ribbed cuffs.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Basic V-Neck Tee',
    brand: 'H&M',
    price: 499,
    category: 'clothes',
    subcategory: 't-shirts',
    gender: 'male',
    colors: ['White', 'Black', 'Gray', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    style: ['minimalist'],
    occasions: ['daily-wear'],
    tags: ['basic', 'v-neck', 'essential'],
    description: 'Essential v-neck tee for everyday wear.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 100,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Slim Fit Blazer',
    brand: 'Hugo Boss',
    price: 8990,
    category: 'clothes',
    subcategory: 'blazers',
    gender: 'male',
    colors: ['Navy', 'Charcoal', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['formal-elegant'],
    occasions: ['work-office', 'wedding-event', 'date-night'],
    tags: ['blazer', 'formal', 'premium'],
    description: 'Premium slim fit blazer for formal occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 15,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Cotton Henley Shirt',
    brand: 'GAP',
    price: 1599,
    category: 'clothes',
    subcategory: 'shirts',
    gender: 'male',
    colors: ['White', 'Navy', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'date-night'],
    tags: ['henley', 'cotton', 'casual'],
    description: 'Comfortable cotton henley with button placket.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Athletic Shorts',
    brand: 'Under Armour',
    price: 1895,
    category: 'clothes',
    subcategory: 'shorts',
    gender: 'male',
    colors: ['Black', 'Gray', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['athleisure'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['athletic', 'shorts', 'moisture-wicking'],
    description: 'Breathable athletic shorts for workouts.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 55,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Knit Sweater',
    brand: 'Uniqlo',
    price: 1990,
    category: 'clothes',
    subcategory: 'sweaters',
    gender: 'male',
    colors: ['Gray', 'Navy', 'Beige'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['smart-casual'],
    occasions: ['work-office', 'daily-wear'],
    tags: ['knit', 'sweater', 'layering'],
    description: 'Soft knit sweater perfect for layering.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Distressed Jeans',
    brand: 'Wrangler',
    price: 2990,
    category: 'clothes',
    subcategory: 'jeans',
    gender: 'male',
    colors: ['Light Blue', 'Medium Blue'],
    sizes: ['28', '30', '32', '34', '36'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'party'],
    tags: ['jeans', 'distressed', 'denim'],
    description: 'Trendy distressed jeans for a casual look.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Linen Shirt',
    brand: 'Mango',
    price: 2495,
    category: 'clothes',
    subcategory: 'shirts',
    gender: 'male',
    colors: ['White', 'Light Blue', 'Beige'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['smart-casual'],
    occasions: ['vacation', 'date-night'],
    tags: ['linen', 'shirt', 'summer'],
    description: 'Breathable linen shirt for warm weather.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Tech Fleece Hoodie',
    brand: 'Nike',
    price: 4295,
    category: 'clothes',
    subcategory: 'hoodies',
    gender: 'male',
    colors: ['Black', 'Gray', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    style: ['athleisure', 'casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['hoodie', 'tech-fleece', 'comfortable'],
    description: 'Premium tech fleece hoodie for ultimate comfort.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Wool Dress Pants',
    brand: 'Ralph Lauren',
    price: 5990,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'male',
    colors: ['Charcoal', 'Navy', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    style: ['formal-elegant'],
    occasions: ['work-office', 'wedding-event'],
    tags: ['wool', 'dress-pants', 'formal'],
    description: 'Elegant wool dress pants for formal occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 20,
    featured: false,
    giftSuitable: true,
  },

  // ==================== WOMEN'S CLOTHING (18 products) ====================
  {
    name: 'Flowy Midi Dress',
    brand: 'Zara',
    price: 2995,
    category: 'clothes',
    subcategory: 'dresses',
    gender: 'female',
    colors: ['Black', 'Floral', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['formal-elegant'],
    occasions: ['date-night', 'wedding-event'],
    tags: ['dress', 'midi', 'elegant'],
    description: 'Elegant flowy midi dress perfect for special occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'High-Waist Skinny Jeans',
    brand: 'Mango',
    price: 2495,
    category: 'clothes',
    subcategory: 'jeans',
    gender: 'female',
    colors: ['Blue', 'Black'],
    sizes: ['24', '26', '28', '30'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'date-night'],
    tags: ['jeans', 'skinny', 'high-waist'],
    description: 'Flattering high-waist skinny jeans with stretch comfort.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Cropped Blazer',
    brand: 'H&M',
    price: 2290,
    category: 'clothes',
    subcategory: 'blazers',
    gender: 'female',
    colors: ['Black', 'Beige'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['smart-casual'],
    occasions: ['work-office', 'date-night'],
    tags: ['blazer', 'cropped', 'professional'],
    description: 'Modern cropped blazer for a polished look.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Basic Cotton Tank Top',
    brand: 'Cotton On',
    price: 599,
    category: 'clothes',
    subcategory: 't-shirts',
    gender: 'female',
    colors: ['White', 'Black', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['tank-top', 'basic', 'cotton'],
    description: 'Essential cotton tank top for everyday wear.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 80,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Pleated Wide-Leg Pants',
    brand: 'Uniqlo',
    price: 1990,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'female',
    colors: ['Navy', 'Cream', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['smart-casual'],
    occasions: ['work-office', 'date-night'],
    tags: ['wide-leg', 'pleated', 'elegant'],
    description: 'Elegant pleated wide-leg pants for a sophisticated look.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Satin Blouse',
    brand: 'Forever 21',
    price: 1199,
    category: 'clothes',
    subcategory: 'blouses',
    gender: 'female',
    colors: ['Champagne', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['formal-elegant'],
    occasions: ['date-night', 'party'],
    tags: ['satin', 'blouse', 'elegant'],
    description: 'Luxurious satin blouse for special occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Knit Cardigan',
    brand: 'Mango',
    price: 2790,
    category: 'clothes',
    subcategory: 'sweaters',
    gender: 'female',
    colors: ['Beige', 'Gray', 'Pink'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['smart-casual'],
    occasions: ['daily-wear', 'work-office'],
    tags: ['cardigan', 'knit', 'cozy'],
    description: 'Cozy knit cardigan perfect for layering.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Wrap Dress',
    brand: 'H&M',
    price: 1990,
    category: 'clothes',
    subcategory: 'dresses',
    gender: 'female',
    colors: ['Red', 'Navy', 'Green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    style: ['smart-casual'],
    occasions: ['work-office', 'date-night'],
    tags: ['wrap', 'dress', 'flattering'],
    description: 'Flattering wrap dress for any occasion.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Yoga Leggings',
    brand: 'Nike',
    price: 2495,
    category: 'clothes',
    subcategory: 'leggings',
    gender: 'female',
    colors: ['Black', 'Gray', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['athleisure'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['leggings', 'yoga', 'athletic'],
    description: 'High-performance yoga leggings with moisture-wicking.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Denim Mini Skirt',
    brand: 'Forever 21',
    price: 999,
    category: 'clothes',
    subcategory: 'skirts',
    gender: 'female',
    colors: ['Light Blue', 'Medium Blue', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'party'],
    tags: ['denim', 'mini', 'skirt'],
    description: 'Classic denim mini skirt for a casual look.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Silk Camisole',
    brand: 'Zara',
    price: 1795,
    category: 'clothes',
    subcategory: 'tops',
    gender: 'female',
    colors: ['White', 'Black', 'Champagne'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['formal-elegant'],
    occasions: ['date-night', 'party'],
    tags: ['silk', 'camisole', 'elegant'],
    description: 'Delicate silk camisole for layering or on its own.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Mom Jeans',
    brand: "Levi's",
    price: 3990,
    category: 'clothes',
    subcategory: 'jeans',
    gender: 'female',
    colors: ['Light Blue', 'Medium Blue'],
    sizes: ['24', '26', '28', '30', '32'],
    style: ['casual-street'],
    occasions: ['daily-wear'],
    tags: ['mom-jeans', 'denim', 'vintage'],
    description: 'Vintage-inspired mom jeans with relaxed fit.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Pencil Skirt',
    brand: 'Mango',
    price: 1990,
    category: 'clothes',
    subcategory: 'skirts',
    gender: 'female',
    colors: ['Black', 'Navy', 'Gray'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['formal-elegant'],
    occasions: ['work-office', 'date-night'],
    tags: ['pencil', 'skirt', 'professional'],
    description: 'Classic pencil skirt for professional settings.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Puff Sleeve Blouse',
    brand: 'H&M',
    price: 1290,
    category: 'clothes',
    subcategory: 'blouses',
    gender: 'female',
    colors: ['White', 'Pink', 'Blue'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['smart-casual'],
    occasions: ['work-office', 'date-night'],
    tags: ['puff-sleeve', 'blouse', 'feminine'],
    description: 'Feminine blouse with trendy puff sleeves.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Maxi Dress',
    brand: 'Cotton On',
    price: 1799,
    category: 'clothes',
    subcategory: 'dresses',
    gender: 'female',
    colors: ['Floral', 'Solid Black', 'Tropical'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    style: ['casual-street'],
    occasions: ['vacation', 'daily-wear'],
    tags: ['maxi', 'dress', 'summer'],
    description: 'Flowy maxi dress for summer days.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Tailored Trousers',
    brand: 'Uniqlo',
    price: 2490,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'female',
    colors: ['Black', 'Camel', 'Gray'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['smart-casual', 'formal-elegant'],
    occasions: ['work-office', 'date-night'],
    tags: ['tailored', 'trousers', 'professional'],
    description: 'Perfectly tailored trousers for the modern woman.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Cropped Denim Jacket',
    brand: 'Zara',
    price: 2990,
    category: 'clothes',
    subcategory: 'jackets',
    gender: 'female',
    colors: ['Light Blue', 'White'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['denim', 'cropped', 'jacket'],
    description: 'Trendy cropped denim jacket.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Bodycon Dress',
    brand: 'Forever 21',
    price: 1499,
    category: 'clothes',
    subcategory: 'dresses',
    gender: 'female',
    colors: ['Black', 'Red', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L'],
    style: ['formal-elegant'],
    occasions: ['party', 'date-night'],
    tags: ['bodycon', 'dress', 'fitted'],
    description: 'Figure-hugging bodycon dress for nights out.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },

  // ==================== UNISEX CLOTHING (6 products) ====================
  {
    name: 'Classic Hoodie',
    brand: 'Champion',
    price: 2990,
    category: 'clothes',
    subcategory: 'hoodies',
    gender: 'unisex',
    colors: ['Gray', 'Navy', 'Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['hoodie', 'classic', 'comfortable'],
    description: 'Classic Champion hoodie with iconic logo.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 60,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Basic Crewneck Sweatshirt',
    brand: 'Uniqlo',
    price: 1490,
    category: 'clothes',
    subcategory: 'sweaters',
    gender: 'unisex',
    colors: ['Gray', 'Black', 'Navy', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['minimalist'],
    occasions: ['daily-wear'],
    tags: ['sweatshirt', 'basic', 'comfortable'],
    description: 'Essential crewneck sweatshirt for everyday comfort.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 70,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Windbreaker Jacket',
    brand: 'Adidas',
    price: 3490,
    category: 'clothes',
    subcategory: 'jackets',
    gender: 'unisex',
    colors: ['Black', 'Navy', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['athleisure', 'casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['windbreaker', 'jacket', 'lightweight'],
    description: 'Lightweight windbreaker for all weather.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Cotton Joggers',
    brand: 'GAP',
    price: 1990,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'unisex',
    colors: ['Gray', 'Black', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['joggers', 'cotton', 'comfortable'],
    description: 'Comfortable cotton joggers for lounging.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Oversized T-Shirt',
    brand: 'Uniqlo',
    price: 790,
    category: 'clothes',
    subcategory: 't-shirts',
    gender: 'unisex',
    colors: ['White', 'Black', 'Beige', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['minimalist'],
    occasions: ['daily-wear'],
    tags: ['oversized', 't-shirt', 'basic'],
    description: 'Relaxed oversized t-shirt in soft cotton.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 80,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Track Pants',
    brand: 'Puma',
    price: 2290,
    category: 'clothes',
    subcategory: 'pants',
    gender: 'unisex',
    colors: ['Black', 'Navy', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    style: ['athleisure'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['track-pants', 'athletic', 'comfortable'],
    description: 'Classic track pants with side stripes.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
  },

  // ==================== SHOES (10 products) ====================
  {
    name: 'Classic White Sneakers',
    brand: 'Converse',
    price: 3490,
    category: 'shoes',
    subcategory: 'sneakers',
    gender: 'unisex',
    colors: ['White'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['sneakers', 'classic', 'canvas'],
    description: 'Timeless classic white sneakers that go with everything.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 60,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Running Shoes',
    brand: 'Nike',
    price: 5495,
    category: 'shoes',
    subcategory: 'running',
    gender: 'unisex',
    colors: ['Black/White', 'Gray/Orange', 'Blue/White'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    style: ['athleisure'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['running', 'athletic', 'comfortable'],
    description: 'Lightweight running shoes with responsive cushioning.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Leather Loafers',
    brand: 'Lacoste',
    price: 6990,
    category: 'shoes',
    subcategory: 'loafers',
    gender: 'male',
    colors: ['Brown', 'Black'],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
    style: ['smart-casual', 'formal-elegant'],
    occasions: ['work-office', 'date-night'],
    tags: ['loafers', 'leather', 'formal'],
    description: 'Premium leather loafers for sophisticated style.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Stan Smith Sneakers',
    brand: 'Adidas',
    price: 4990,
    category: 'shoes',
    subcategory: 'sneakers',
    gender: 'unisex',
    colors: ['White/Green', 'White/Navy'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
    style: ['casual-street', 'minimalist'],
    occasions: ['daily-wear', 'date-night'],
    tags: ['sneakers', 'classic', 'iconic'],
    description: 'Iconic Stan Smith sneakers in classic white leather.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Ankle Boots',
    brand: 'Zara',
    price: 4990,
    category: 'shoes',
    subcategory: 'boots',
    gender: 'female',
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['35', '36', '37', '38', '39', '40'],
    style: ['smart-casual'],
    occasions: ['daily-wear', 'date-night'],
    tags: ['boots', 'ankle', 'leather'],
    description: 'Versatile ankle boots for any occasion.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Slip-On Sneakers',
    brand: 'Vans',
    price: 2990,
    category: 'shoes',
    subcategory: 'sneakers',
    gender: 'unisex',
    colors: ['Black', 'White', 'Checkerboard'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['slip-on', 'sneakers', 'classic'],
    description: 'Classic slip-on sneakers for effortless style.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 55,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Heeled Sandals',
    brand: 'Mango',
    price: 3290,
    category: 'shoes',
    subcategory: 'sandals',
    gender: 'female',
    colors: ['Black', 'Nude', 'Gold'],
    sizes: ['35', '36', '37', '38', '39', '40'],
    style: ['formal-elegant'],
    occasions: ['date-night', 'wedding-event', 'party'],
    tags: ['heels', 'sandals', 'elegant'],
    description: 'Elegant heeled sandals for special occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 25,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Canvas Espadrilles',
    brand: 'H&M',
    price: 1490,
    category: 'shoes',
    subcategory: 'flats',
    gender: 'female',
    colors: ['White', 'Navy', 'Red'],
    sizes: ['35', '36', '37', '38', '39', '40'],
    style: ['casual-street'],
    occasions: ['vacation', 'daily-wear'],
    tags: ['espadrilles', 'canvas', 'summer'],
    description: 'Casual canvas espadrilles for summer.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Oxford Dress Shoes',
    brand: 'Marks & Spencer',
    price: 5490,
    category: 'shoes',
    subcategory: 'oxfords',
    gender: 'male',
    colors: ['Black', 'Brown'],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
    style: ['formal-elegant'],
    occasions: ['work-office', 'wedding-event'],
    tags: ['oxford', 'dress-shoes', 'formal'],
    description: 'Classic oxford dress shoes for formal occasions.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 20,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Platform Sneakers',
    brand: 'Fila',
    price: 4490,
    category: 'shoes',
    subcategory: 'sneakers',
    gender: 'female',
    colors: ['White', 'Black', 'Pink'],
    sizes: ['35', '36', '37', '38', '39', '40'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'party'],
    tags: ['platform', 'sneakers', 'chunky'],
    description: 'Trendy platform sneakers for a bold look.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },

  // ==================== ACCESSORIES (8 products) ====================
  {
    name: 'Leather Belt',
    brand: 'Lacoste',
    price: 2500,
    category: 'accessories',
    subcategory: 'belts',
    gender: 'unisex',
    colors: ['Brown', 'Black'],
    sizes: ['S', 'M', 'L'],
    style: ['smart-casual', 'formal-elegant'],
    occasions: ['work-office', 'date-night'],
    tags: ['belt', 'leather', 'classic'],
    description: 'Premium leather belt with signature crocodile buckle.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 45,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Canvas Backpack',
    brand: 'Herschel',
    price: 3990,
    category: 'accessories',
    subcategory: 'bags',
    gender: 'unisex',
    colors: ['Navy', 'Gray', 'Black'],
    sizes: ['One Size'],
    style: ['casual-street'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['backpack', 'canvas', 'durable'],
    description: 'Durable canvas backpack for everyday adventures.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Minimalist Watch',
    brand: 'Casio',
    price: 2995,
    category: 'accessories',
    subcategory: 'watches',
    gender: 'unisex',
    colors: ['Silver', 'Gold', 'Black'],
    sizes: ['One Size'],
    style: ['minimalist', 'smart-casual'],
    occasions: ['work-office', 'date-night'],
    tags: ['watch', 'minimalist', 'classic'],
    description: 'Clean minimalist watch for any occasion.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 40,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Crossbody Bag',
    brand: 'Coach',
    price: 8990,
    category: 'accessories',
    subcategory: 'bags',
    gender: 'female',
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['One Size'],
    style: ['smart-casual'],
    occasions: ['daily-wear', 'date-night'],
    tags: ['crossbody', 'bag', 'leather'],
    description: 'Elegant leather crossbody bag.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 20,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Aviator Sunglasses',
    brand: 'Ray-Ban',
    price: 7990,
    category: 'accessories',
    subcategory: 'eyewear',
    gender: 'unisex',
    colors: ['Gold/Green', 'Silver/Blue', 'Black'],
    sizes: ['One Size'],
    style: ['casual-street', 'smart-casual'],
    occasions: ['vacation', 'daily-wear'],
    tags: ['sunglasses', 'aviator', 'classic'],
    description: 'Iconic aviator sunglasses with UV protection.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 30,
    featured: true,
    giftSuitable: true,
  },
  {
    name: 'Silk Scarf',
    brand: 'Zara',
    price: 1490,
    category: 'accessories',
    subcategory: 'scarves',
    gender: 'female',
    colors: ['Floral', 'Geometric', 'Solid Red'],
    sizes: ['One Size'],
    style: ['smart-casual', 'formal-elegant'],
    occasions: ['work-office', 'date-night'],
    tags: ['scarf', 'silk', 'elegant'],
    description: 'Elegant silk scarf for versatile styling.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 35,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Leather Wallet',
    brand: 'Tommy Hilfiger',
    price: 3490,
    category: 'accessories',
    subcategory: 'wallets',
    gender: 'male',
    colors: ['Black', 'Brown'],
    sizes: ['One Size'],
    style: ['smart-casual'],
    occasions: ['daily-wear'],
    tags: ['wallet', 'leather', 'bifold'],
    description: 'Classic leather bifold wallet.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 50,
    featured: false,
    giftSuitable: true,
  },
  {
    name: 'Baseball Cap',
    brand: 'Nike',
    price: 1290,
    category: 'accessories',
    subcategory: 'hats',
    gender: 'unisex',
    colors: ['Black', 'White', 'Navy'],
    sizes: ['One Size'],
    style: ['casual-street', 'athleisure'],
    occasions: ['daily-wear', 'vacation'],
    tags: ['cap', 'baseball', 'swoosh'],
    description: 'Classic Nike cap with embroidered swoosh.',
    images: ['/placeholder-product.jpg'],
    inStock: true,
    stockQty: 60,
    featured: false,
    giftSuitable: true,
  },
]
